name: Version

on:
  push:
    branches:
      - "master"

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore(release): publish')"
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 30
          continue-after-seconds: 180
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name '@jakehamilton'
          git config --global user.email 'jakehamilton@users.noreply.github.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GH_TOKEN@github.com/jakehamilton/packages
      - name: Update History and Tags
        run: |
          git checkout "${GITHUB_REF:11}" && git pull
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Configure NPM
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken=\${NPM_TOKEN}
      - name: Check Authentication with Registry
        run: npm whoami
      - name: Install Dependencies
        run: npm install --no-save
      - name: Bootstrap
        run: |
          npm run ci:bootstrap
          npm run ci:build
      - name: Version Packages
        run: npm run ci:version
      - name: Publish Packages
        run: npm run ci:publish
      - name: Build Documentation
        run: npm run docs:build
        env:
          BASE_URL: "/packages/"
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
